### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by niccokunzmann** [mip-tv/server#1]
I would like to host this at home. However, I will need a Dockerfile/build for this.
Is this a usual np install and it works? Does it require a database?

**Comment by mgjm** [comment]
The server uses Cassandra as a database and we will upload a docker compose file later

**Comment by niccokunzmann** [comment]
#2 creates the docker file.
However, I would like to use an automatically built image. I can build it myself but would it be possible, to add an automated build for the latest version?

**Comment by mgjm** [comment]
I just accepted your PR and added some changes to the Dockerfile in 832c6b1 and I will setup an automated build later.
